timeout(time: 20, unit: 'MINUTES') {
node() {
    stage('Code Checkout') {
        sh " rm -rf *" 
        sh " docker system prune -af"
        sh 'git clone https://github.com/srijondasgit/examfrontend.git'
    
}
dir('examfrontend/exammodule') {


stage('Docker Login') {
    withCredentials([string(credentialsId: 'dhub_user', variable: 'USERID'),string(credentialsId: 'dhub_pwd', variable: 'PASSWORD')]) {
        sh "docker login -u ${USERID} -p ${PASSWORD}"

    }
}

stage('Docker Build') {
    sh "docker build -t exfront-gitanjali ."
}
stage('Tag Image') {
    sh "docker tag exfront-gitanjali:latest srijondas/production-exfront-gitanjali:latest"
}
stage('Pushing Image To DockerHub') {
 sh " docker push srijondas/production-exfront-gitanjali:latest"
}
}
}
}
